# ⚠️ Only non-root builds.

parallel-jobs = 1

[YT] # Default patches are applied, Except line 7 and 8 :
rv-brand = "Morphe"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/morphe_play/'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Revancify] # Same patches applied as before, but with Extended icon:
rv-brand = "Blue"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/revancify_blue/'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Music] is no longer available :
# use [Metrolist](https://github.com/MetrolistGroup/Metrolist/releases/latest),
# or [OpenTune](https://github.com/Arturo254/OpenTune/releases/latest) instead.
