# ⚠️ Only non-root builds.

parallel-jobs = 1

[YT] # Default patches are applied, Except line 7 and 8 :
rv-brand = "Morphe"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/morphe_play/'"
uapkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YT-Revancify] # Same patches applied as before, but with Extended icon:
rv-brand = "Blue"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/revancify_blue/'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

# [Music] is no longer available :
# use Metrolist instead: https://github.com/MetrolistGroup/Metrolist .
