name: Canary
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
    - cron: "17 * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.schedule }} $(date -u)"